### ISSUE TITLE
[FEAT] 루틴 최대 등록 개수 및 indicator 추가

### ISSUE THREAD

**Issue by yurabahng** [routinder/routinder_front#29]
## SUMMARY

사용자당 등록 가능한 루틴 최대 개수 지정 이슈 대응.
[https://github.com/routinder/routinder_server/issues/18#issue-1291976187](url)

1. acitve 루틴 개수는 10개로 제한 (하루당 등록하는 루틴 개수 제한 정책은 삭제.)
2. indicator를 캘린더에 표시.

## CHECKLIST
- [x] 정책 추가 및 기획서 업데이트.
- [x] indicator 캘린더에 표시.

## ETC

대응방식 검토 요청 예정.

**Comment by yurabahng** [comment]
1. month calendar 칸은 최대 4개 출력.  week calendar 칸에는 최대 6개 출력. 그 이상 넘어가면 인디케이터 표시.
2. active 루틴 (=기간이 종료되지 않은 루틴) 은 최대 10개로 제한 (논의내용 반영.)
![AS-IS 6개, TO-BE 8개 + indicator](https://user-images.githubusercontent.com/82425858/185775084-8bbb637c-ef1b-4aae-91e3-9f83bf48186a.png)
![AS-IS 6개, TO-BE 4개 + indicator](https://user-images.githubusercontent.com/82425858/185775086-8d57ae29-1f2c-4c84-8d17-37df15f721a6.png)

**Comment by pje1740** [comment]
지금은 MonthlyCalendar가 기존처럼 6개 노출로 구현되어 있어서 UI 작업할 때 일괄적으로 수정할게요!

**Comment by yurabahng** [comment]
@pje1740  @jiyoon1156 
앗 네네 감사합니다~!!
디자인이랑 간격 수정해서 제플린에 업로드해두었습니다~
아래 링크 참고 부탁드려요 :)

📌정책
1. MonthlyCalendar: 최대 4개 출력. 그 이상은 인디케이터 표시.
2. WeeklyCalendar: 최대 6개 출력. 그 이상은 인디케이터 표시.

📌제플린 링크
https://zpl.io/6NeD1Ny

📌이미지
![weekly calendar_indicator](https://user-images.githubusercontent.com/82425858/185907917-a206d968-712c-4985-895c-5b66cc7854e8.jpg)

![monthly calendar_indicator](https://user-images.githubusercontent.com/82425858/185907977-8df961f5-a165-4ce8-83ce-065ad743e92a.jpg)

**Comment by yurabahng** [comment]
@pje1740 님, @jiyoon1156 님
해당 이슈 대응하기 위한 디자인 작업을 완료했으며, 이슈 close 할게요~!!
